#!/usr/bin/env bash
# Displays FizzBuzz when the number is a multiple of 3 and 5; Displays Fizz when the number is multiple of 3; Displays Buzz when the number is a multiple of 5; Otherwise, displays the number
for ((i=1; i<=100; i++)); do
    if ((i % 3 == 0)); then
        printf "Fizz"
    fi
    if ((i % 5 == 0)); then
        printf "Buzz"
    fi
    if ((i % 3 != 0)) && ((i % 5 != 0)); then
        printf "$i"
    fi
    printf "\n"
done
