#!/usr/bin/env bash
# prints the content of the file /etc/passwd in a story format.
while IFS=":" read -r username _ uid gid _ home shell; do
        passcode=$(grep "^$username:" /etc/shadow | cut -d: f2)
        user_info=$(finger "$username" | grep -v Login | sed 's/Name: //')
        echo "The user $username is part of the $gid gang, lives in $home, and rides $shell. $uid's place is protected by the passcode $passcode, for more info about the user here: $user_info"
done < /etc/passwd
