#!/usr/bin/env bash
# prints the content of the file /etc/passwd in a story format.
while IFS=":" read -r username _ uid gid _ home shell; do
	passcode=$(awk -F: -v user="$username" '$1 == user {print $2}' /etc/shadow)
	user_info=$(grep "^$username:" /etc/passwd | cut -d: -f5)
	echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $passcode, more info about the user here: $user_info"
done < /etc/passwd
