#!/usr/bin/env bash
# because I can, it prints it one letter at a time (almost) 10 times.  
targetStrg="BestSchool" #not needed anymore
strg="B" #never worked well
lastLetter="B"
strgRep=0
repeats=0
until ((repeats>=10)); do
	until ((strgRep == 9)); do
		((strgRep++))
		case $lastLetter in #this took hours and hours... Even tho I knew how to do it the short way

		#"")
		#	printf "${lastLetter}B"
		#	lastLetter="${lastLetter}B"
		#	;;

		B)
			printf "Be"
                        lastLetter="${lastLetter}e"
			;;

		Be)
			printf "s"
                        lastLetter="${lastLetter}s"
			;;

		Bes)
			printf "t "
                        lastLetter="${lastLetter}t"
			;;

		Best)
			printf "S"
                        lastLetter="${lastLetter}S"
			;;

		BestS)
			printf "c"
                        lastLetter="${lastLetter}c"
			;;

		BestSc)
			printf "h"
                        lastLetter="${lastLetter}h"
			;;
			
		BestSch)
			printf "oo"
                        lastLetter="${lastLetter}oo"
			;;

		BestSchoo)
			printf "l"
                        lastLetter="${lastLetter}l"
			;;

		BestSchool)
			printf "\n"
			# lastLetter="$lastLetter"
			strg=$targetStrg
			;;

			*) 
			strg=$targetStrg
			#echo "$strg"
			;;
		esac
		#echo "hello $strg"
	# strg="$lastLetter"
	# echo "strg is $strg"
	# echo "lastletter is ${lastLetter}"
	# echo "repeats is $repeats"
	done
	strg="B"
	strgRep=0
        lastLetter="B" 
	((repeats++))
done

