#!/usr/bin/env bash
# Repeat This a total of 10 times. n = how many times it's repeated. If n equals 4, print bad luck, if 8, print good luck, else, print Best School.
n=1
while ((n<=10)); 
	do case $n in

		4)
			echo "Bad Luck"
		;;

		8)
			echo "Good Luck"
		;;

		*)
			echo "Best School"
		;;
	esac
((n++)) 
done

