#!/usr/bin/env bash
# Repeat This a total of 20 times. n = how many times it's repeated. Print n. If n equals 4, also add bad luck from China, if 9, print bad luck from Japan, if 17, bad luck from Italy, else, just print the value of n.
n=1
while (($n<=20));
	echo $n
        do case $n in

                4)
                        echo "bad luck from China"
                ;;

                9)
                        echo "bad luck from Japan"
                ;;

		17)
			echo "bad luck from Italy"
		;;

        esac
((n++))
done
