#!/usr/bin/env bash
# displays 59 minutes for every hour, with 13 (0-12) hours 
hours=0
minutes=1

while ((hours<=12)); do
	echo "Hour: $hours"
	while ((minutes<=59)); do
        	echo "$minutes"
        	((minutes++))
	done
	if (($minutes >=60)); then
                        minutes=1
                fi
	((hours++))
done
