#!/usr/bin/env bash
# check if file exists, check if file is empty, check if file is a regular file, and print the coreect respective messages. 
file="school"

if [ -e "$file" ]; then
    echo "school file exists"

    if [ -s "$file" ]; then
        echo "school file is not empty"
    else
        echo "school file is empty"
    fi

    if [ -f "$file" ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
